const answer =
    document.getElementById("cardAnswer");

const showBtn =
    document.getElementById("showBtn");

const nextBtn =
    document.getElementById("nextBtn");

const prevBtn =
    document.getElementById("prevBtn");

const menuBtn =
    document.getElementById("menuBtn");

const sidebar =
    document.querySelector(".sidebar");


/* SHOW ANSWER */

showBtn.addEventListener("click", function () {

    answer.textContent =
        "RAG combines an AI model with external information retrieval so the model can use relevant documents when generating an answer.";

});


/* NEXT */

nextBtn.addEventListener("click", function () {

    alert("Next flashcard will be generated by the backend.");

});


/* PREVIOUS */

prevBtn.addEventListener("click", function () {

    alert("Previous flashcard will be loaded here.");

});


/* MOBILE SIDEBAR */

menuBtn.addEventListener("click", function () {

    sidebar.classList.toggle("open");

});