const options =
    document.querySelectorAll(".option");

const nextBtn =
    document.getElementById("nextBtn");

const menuBtn =
    document.getElementById("menuBtn");

const sidebar =
    document.querySelector(".sidebar");


/* SELECT ANSWER */

options.forEach(function (option) {

    option.addEventListener("click", function () {

        options.forEach(function (item) {
            item.classList.remove("selected");
        });

        option.classList.add("selected");

    });

});


/* NEXT QUESTION */

nextBtn.addEventListener("click", function () {

    alert("Next question will be generated by the backend.");

});


/* MOBILE SIDEBAR */

menuBtn.addEventListener("click", function () {

    sidebar.classList.toggle("open");

});